sync commits from internal cloud-controller-manager repo
Enable provisioning BV from another BV

Fix review comments

Fix review comments

Add unit tests

Deploy single container with CCM and FVP

Fix polling error

fix review comments

Refactored to move command to app package, replace fatalf refrences with error, remove nodeName reference

Cert rotation should avoid listener recreation

fix review comments

match params with called func signature

Signed-off-by: Steve Brunton <steve.brunton@oracle.com>

Fix test to avoid appending secret name to listeners name

correction to boilerplate header validation and remove e2e test automation

OKE-8694 - CCM is not honouring oci-load-balancer-connection-idle-timeout annotation during update event

OKE-8991: add/delete/update backend servers instead of updating the entire backendsets

JIRA: OKE-9388 - [TKM] [TKW] Migrate oci-cloud-controller-manager to use Go SDK v17.0.0 or greater.

OKE-9846: 1. CCM is calling update listener in time of new events
2. Adding logs to show the difference between the spec and LB in time of UpdateListener and UpdatebackendSet 3. Add Backend name in Backend creation log

OKE-9860 - Remove CCM internal rate limiting by adding a backward compatible option

JIRA: OKE-10232 - Investigate and fix the storage tests in CCM repo

JIRA: OKE-10232 - Investigate and fix the storage tests in CCM repo

JIRA: OKE-9860 Remove CCM internal rate limiting by adding a backward compatible option. refactoring NewRateLimiter in cloud_provider_framework.go

correct the copyright

remove lint error

Add documentation for 1.16 support and missing FVD and FVP installation

1.17 supported change in readme

JIRA: OKE-8771 Change documentation as per new release. remove real ocids

make changes to push to oss repo

diff --git a/wercker.yml b/wercker.yml
--- a/wercker.yml
+++ b/wercker.yml
@@ -1,4 +1,4 @@
-box: iad.ocir.io/spinnaker/oci-kube-ci:1.0.3
+box: iad.ocir.io/odx-mockcustomer/oci-kube-ci:1.0.4
 no-response-timeout: 30
 command-timeout: 30
 
@@ -75,72 +75,72 @@ publish-docker-image:
             docker push ${IMAGE}:latest
           fi
 
-ccm-e2e-test:
-  base-path: "/go/src/github.com/oracle/oci-cloud-controller-manager"
-  steps:
-    - script:
-      name: Run CCM E2E tests
-      code: |
-        export VERSION=$(make version)
-        echo "Running CCM tests version: ${VERSION}"
-        export NODEPORT_TEST="true"
-        export CCM_SECLIST_ID="ocid1.securitylist.oc1.iad.aaaaaaaagekgnvc75yxb66xj2qgocejhyk5xuhojm6wimmteqa5fj43kk5lq"
-        export K8S_SECLIST_ID="ocid1.securitylist.oc1.iad.aaaaaaaajzgrgfma2xzzdv4erczaiphuyaflazbt2bvzw2cwj2pxo3fygo5a"
-
-        if [ -z "${KUBECONFIG}" ]; then
-            if [ -z "${KUBECONFIG_VAR}" ]; then
-                echo "KUBECONFIG or KUBECONFIG_VAR must be set"
-                exit 1
-            else
-                # NB: Wercker environment variables are base64 encoded.
-                echo "$KUBECONFIG_VAR" | openssl enc -base64 -d -A > /tmp/kubeconfig
-                export KUBECONFIG=/tmp/kubeconfig
-            fi
-        fi
-
-        if [ -z "${CLOUDCONFIG}" ]; then
-            if [ -z "${CLOUDCONFIG_VAR}" ]; then
-                echo "CLOUDCONFIG or CLOUDCONFIG_VAR must be set"
-                exit 1
-            else
-                # NB: Wercker environment variables are base64 encoded.
-                echo "$CLOUDCONFIG_VAR" | openssl enc -base64 -d -A > /tmp/cloudconfig
-                export CLOUDCONFIG=/tmp/cloudconfig
-            fi
-        fi
-
-        ginkgo                                 \
-          -v                                   \
-          -progress                            \
-          test/e2e/cloud-controller-manager -- \
-          --kubeconfig=${KUBECONFIG}           \
-          --cloud-config=${CLOUDCONFIG}        \
-          --delete-namespace=true
-
-volume-provisioner-e2e-test:
-  base-path: "/go/src/github.com/oracle/oci-cloud-controller-manager"
-  steps:
-    - script:
-      name: Run volume provisioner E2E tests
-      code: |
-        export VERSION=$(cat dist/VERSION.txt)
-
-        export OCI_CONFIG="/tmp/ociconfig"
-        echo -n "${OCI_CONFIG_VAR}" | openssl enc -base64 -d -A > "${OCI_CONFIG}"
-
-        export KUBECONFIG="/tmp/kubeconfig"
-        echo -n "${KUBECONFIG_VAR}" | openssl enc -base64 -d -A > "${KUBECONFIG}"
-
-        export MOUNT_TARGET_ID="ocid1.mounttarget.oc1.iad.aaaaaby27vezbb5cnfqwillqojxwiotjmfsc2ylefuzqaaaa"
-
-        ginkgo \
-          -v \
-          test/e2e/volume-provisioner -- \
-          --kubeconfig="${KUBECONFIG}" \
-          --ociconfig="${OCI_CONFIG}" \
-          --mnt-target-id="${MOUNT_TARGET_ID}" \
-          --delete-namespace-on-failure=true \
-          --image="iad.ocir.io/oracle/cloud-provider-oci:${VERSION}"
+#ccm-e2e-test:
+#  base-path: "/go/src/github.com/oracle/oci-cloud-controller-manager"
+#  steps:
+#    - script:
+#      name: Run CCM E2E tests
+#      code: |
+#        export VERSION=$(make version)
+#        echo "Running CCM tests version: ${VERSION}"
+#        export NODEPORT_TEST="true"
+#        export CCM_SECLIST_ID="ocid1.securitylist.oc1.iad.aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa"
+#        export K8S_SECLIST_ID="ocid1.securitylist.oc1.iad.aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa"
+#
+#        if [ -z "${KUBECONFIG}" ]; then
+#            if [ -z "${KUBECONFIG_VAR}" ]; then
+#                echo "KUBECONFIG or KUBECONFIG_VAR must be set"
+#                exit 1
+#            else
+#                # NB: Wercker environment variables are base64 encoded.
+#                echo "$KUBECONFIG_VAR" | openssl enc -base64 -d -A > /tmp/kubeconfig
+#                export KUBECONFIG=/tmp/kubeconfig
+#            fi
+#        fi
+#
+#        if [ -z "${CLOUDCONFIG}" ]; then
+#            if [ -z "${CLOUDCONFIG_VAR}" ]; then
+#                echo "CLOUDCONFIG or CLOUDCONFIG_VAR must be set"
+#                exit 1
+#            else
+#                # NB: Wercker environment variables are base64 encoded.
+#                echo "$CLOUDCONFIG_VAR" | openssl enc -base64 -d -A > /tmp/cloudconfig
+#                export CLOUDCONFIG=/tmp/cloudconfig
+#            fi
+#        fi
+#
+#        ginkgo                                 \
+#          -v                                   \
+#          -progress                            \
+#          test/e2e/cloud-controller-manager -- \
+#          --kubeconfig=${KUBECONFIG}           \
+#          --cloud-config=${CLOUDCONFIG}        \
+#          --delete-namespace=true
+#
+#volume-provisioner-e2e-test:
+#  base-path: "/go/src/github.com/oracle/oci-cloud-controller-manager"
+#  steps:
+#    - script:
+#      name: Run volume provisioner E2E tests
+#      code: |
+#        export VERSION=$(cat dist/VERSION.txt)
+#
+#        export OCI_CONFIG="/tmp/ociconfig"
+#        echo -n "${OCI_CONFIG_VAR}" | openssl enc -base64 -d -A > "${OCI_CONFIG}"
+#
+#        export KUBECONFIG="/tmp/kubeconfig"
+#        echo -n "${KUBECONFIG_VAR}" | openssl enc -base64 -d -A > "${KUBECONFIG}"
+#
+#        export MOUNT_TARGET_ID="ocid1.mounttarget.oc1.iad.aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa"
+#
+#        ginkgo \
+#          -v \
+#          test/e2e/volume-provisioner -- \
+#          --kubeconfig="${KUBECONFIG}" \
+#          --ociconfig="${OCI_CONFIG}" \
+#          --mnt-target-id="${MOUNT_TARGET_ID}" \
+#          --delete-namespace-on-failure=true \
+#          --image="iad.ocir.io/oracle/cloud-provider-oci:${VERSION}"
 
 release:
   box:
